# -*- coding: utf-8 -*-
"""ML.projectfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovqQdF16CGZXlpfVLptWliL9Qs53E4QK
"""

import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

mnist= fetch_openml('mnist_784', version=1, as_frame=False)

x = mnist.data
y = mnist.target.astype(int)
x = x / 255.0

x_train, x_test, y_train, y_test = train_test_split(x,y , test_size=0.2, random_state=42)

log_clf = LogisticRegression(
    solver='lbfgs',
    max_iter=200,
    n_jobs=-1
)

log_clf.fit(x_train, y_train)
log_pred = log_clf.predict(x_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, log_pred))

scaler = StandardScaler()

# Use smaller subset for training
X_train_small = x_train[:10000]
y_train_small = y_train[:10000]
x_train_scaled_small = scaler.fit_transform(X_train_small)

# Scale full test set
x_test_scaled = scaler.transform(x_test)

# Train SVM
svm_clf = SVC(kernel='rbf', gamma='scale')
svm_clf.fit(x_train_scaled_small, y_train_small)

# Predict
svm_pred = svm_clf.predict(x_test_scaled)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, log_pred)  # for logistic regression
sns.heatmap(cm, annot=True, fmt='d')
plt.show()

import matplotlib.pyplot as plt

for i in range(5):
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title(f"Pred: {log_pred[i]}, True: {y_test[i]}")
    plt.show()

print("Support Vector Machine (SVM) Accuracy:", accuracy_score(y_test, svm_pred))